Repository holidaygarrison/Group3, pull requests merged in 2022-11, with the labels that each got.

#66 Add more fields to create account page
  createAccount.php
Labels: development

#64 Posts' Special Characters Issues
  AcceptRequestPro.php
  DeclineRequestPro.php
  FriendAcceptPro.php
  FriendRequestPro.php
  RemoveFriendPro.php
  createAccount.php
  createAccountPro.php
  inc/menu.php
  index.php
  lib/accounts_class.php
  lib/friends_class.php
  lib/posts_class.php
  login.php
  loginPro.php
  logout.php
  newlogin.php
  profile.php
Labels: bug

#73 Add edit account details button and form skeleton
  profile.php
Labels: enhancement
